#!/bin/sh

# BUNDLE="`echo "$0" | sed -e 's/\/Contents\/MacOS\/.*//'`"
# RESOURCES="$BUNDLE/Contents/Resources"

# echo "BUNDLE: $BUNDLE"
# echo "RESOURCES: $RESOURCES"

# export DYLD_LIBRARY_PATH=$RESOURCES/lib

# exec "$RESOURCES/bin/Executable"
cd $(dirname "$0")

ROOT_DIR=`pwd`
echo "$0">>/Users/tumi/source/github/log.txt